### ISSUE TITLE
Total implementations aren't considered total

### ISSUE THREAD

**Issue by joelberkeley** [Z-snails/Idris2-hashable#4]
It looks to me like `Hashable Int` etc. are all total but Idris only considers them covering. I've looked at a number of approaches to making them obviously total

In my project, my approach has been to define my own, local wrappers of these implementations. This has the problem that `Hashable` is in the same namespace as `Hashable Int` so Idris can't resolve the interface. This could be fixed by either moving the implementations into a separate module from the interface, or marking the library implementations total.

We could do this by either adding `assert_total` in this library, or using a little refactoring like
```
export
defaultHashWithSalt : (a -> Bits64) -> Bits64 -> a -> Bits64
defaultHashWithSalt hash salt x = salt `combine` hash x

export total
Hashable Bits8 where
    hash = cast
    hashWithSalt = defaultHashWithSalt hash
```
although I imagine `Hashable a =>` makes for a nicer API

**Comment by Z-snails** [comment]
I'm happy for you to make the interface `total` and fix all the errors that makes. If you need to refactor `defaultHashWithSalt` that's ok with me.

I don't really know what I'm doing when it comes to hashing, I mostly just copied the haskell library, so feel free to suggest (or even better, make) changes please do.

**Comment by joelberkeley** [comment]
this looks completed, so I'll close it
